name: Python package

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv
        run: pip install uv
      - name: Install dependencies
        run: |
          uv venv --python 3.11 .venv
          source .venv/bin/activate
          uv pip install -r requirements.txt
      - name: Run tests
        run: |
          source .venv/bin/activate
          python -m pytest -v